version: '3.8'

services:
  postgres:
    image: postgres
    container_name: storageStock
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
